### ISSUE TITLE
Comment & Sidebar text colors are unaffected by color_text on black background

### ISSUE THREAD

**Issue by vegax87** [12px/eddited#5]
I'm trying to customize my subreddit theme with the web compiler (v.1.0.0-RC3) in this way: with a white text on black background, but I noticed that the comment & sidebar text colors still appear **dark grey** and they're  unaffected by color_text
```
{
  "color_accent": "#ffffff",
  "color_background": "#000000",
  "color_text": "#ffffff",
  "color_text_subtle": "#ffffff",
  "color_shadow": "#f7f7f7",
  "color_border": "#ffffff",
...
}
```

**Comment by 12px** [comment]
Fixed in [this commit](https://github.com/12px/eddited/commit/e66c62cc76fdc17923aa53409eea4228592edbb3).
